apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger-deployment
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      run: triggers
  template:
    metadata:
      labels:
        run: triggers
    spec:
      containers:
        - name: trigger
          image: phutanevinayakdocker/triggers:latest
          env:
            - name: MONGO_URI
              value: "xxxx"
            - name: POLLER_INTERVAL
              value: "30000"
            - name: BROKER
              value: "kafka-cluster-kafka-0.kafka-cluster-kafka-brokers.kafka.svc:9092"
            - name: KAFKA_TOPIC
              value: "event-queue"
          # resources:
          #   requests:
          #     memory: "256Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
    